// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lbFH1X-HtVggcSQ58kfuvlKeWFKz-lM',
    appId: '1:539697623189:web:f849cf79d16fd748f9ab9c',
    messagingSenderId: '539697623189',
    projectId: 'monthly-report-ab2b6',
    authDomain: 'monthly-report-ab2b6.firebaseapp.com',
    storageBucket: 'monthly-report-ab2b6.appspot.com',
    measurementId: 'G-SGLZH4J0YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjt38E2Xvt-TrL_F7U5hpWDVSAbXBrOtI',
    appId: '1:539697623189:android:091f3bceb4a3a11ff9ab9c',
    messagingSenderId: '539697623189',
    projectId: 'monthly-report-ab2b6',
    storageBucket: 'monthly-report-ab2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXrpQ-CDkfoNooVmP77jFOnQ_iheOWwA',
    appId: '1:539697623189:ios:6b2a89a9fe1e00e9f9ab9c',
    messagingSenderId: '539697623189',
    projectId: 'monthly-report-ab2b6',
    storageBucket: 'monthly-report-ab2b6.appspot.com',
    iosClientId: '539697623189-bmjirb7mcn3n4n6e4k1r1641v72j065p.apps.googleusercontent.com',
    iosBundleId: 'com.example.monthlyReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoXrpQ-CDkfoNooVmP77jFOnQ_iheOWwA',
    appId: '1:539697623189:ios:6b2a89a9fe1e00e9f9ab9c',
    messagingSenderId: '539697623189',
    projectId: 'monthly-report-ab2b6',
    storageBucket: 'monthly-report-ab2b6.appspot.com',
    iosClientId: '539697623189-bmjirb7mcn3n4n6e4k1r1641v72j065p.apps.googleusercontent.com',
    iosBundleId: 'com.example.monthlyReport',
  );
}
